Formula/cockroach.rb
For [1.0-rc.2 release](https://github.com/cockroachdb/cockroach/issues/15660)
=> Upgrade homebrew formula to 1.0-rc.2

Formula/cockroach.rb
```
$ wget https://binaries.cockroachdb.com/cockroach-v1.0.src.tgz
2017-05-10 09:30:26 (18.3 MB/s) - ‘cockroach-v1.0.src.tgz’ saved
[68753479/68753479]
$ sha2 cockroach-v1.0.src.tgz
SHA-256 (cockroach-v1.0.src.tgz) =
ca87b10eec688195e0df4f85431b019f2980ae4b511ee321f91f945315efeb76
SHA-384 (cockroach-v1.0.src.tgz) =
852945017c596e75fd48f6c528f39a347b47f86e20d7eb2d6d6e366047f9dd7492f794d5ee90153a21b7dec1bd59b29d
SHA-512 (cockroach-v1.0.src.tgz) =
d74ad9546908535f9a7ad4172a04a5f86f5ed22698bbb005aec7478a52632e0497a966b859fd68b40894eb7ee68bfa80dc4188d198f2f23725b9cadd50a55191
```
=> Update brew formula for 1.0

README.md
=> Rename repo to homebrew-tap

Formula/cockroach.rb
```
$ curl https://binaries.cockroachdb.com/cockroach-${TAG}.darwin-10.9-amd64.tgz | shasum -a 256
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 53.1M  100 53.1M    0     0  21.8M      0  0:00:02  0:00:02 --:--:-- 21.8M
bbe3a03c661555e8b083856c56c8a3b459f83064d1d552ed3467cbfb66e76db7  -
```
=> Update homebrew formula to 20.2.5

Formula/cockroach.rb
```
curl https://binaries.cockroachdb.com/cockroach-v20.2.6.darwin-10.9-amd64.tgz |shasum -a 256
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 53.2M  100 53.2M    0     0  17.1M      0  0:00:03  0:00:03 --:--:-- 17.1M
1068d49267a0344de93b33051b99bd0136dd03c68c4d8a606ef4bf462f6a8fa7  -
```
=> Update homebrew formula to 20.2.6

Formula/cockroach-sql.rb, release/ccloud-tmpl.rb, release/cockroach-sql-tmpl.rb, release/cockroach-tmpl.rb, release/main.go
=> Add cockroach-sql formula

Formula/cockroach.rb
Not working on ARM due to incorrect signing.
=> install geos libs only on intel macs

Formula/cockroach-sql.rb, Formula/cockroach.rb, release/cockroach-tmpl.rb
This updates the formula template to incorporate changes from #123 and regenerates the formula for 22.2.1
=> Update formula template to incorporate changes from #123

release/main.go
See https://github.com/cockroachdb/cockroach/issues/94441 for the details.
=> Arm64 tarball name change

Formula/cockroach-sql.rb, Formula/cockroach.rb
Reverts cockroachdb/homebrew-tap#132
=> Revert "Version bump for v22.2.4"

.github/workflows/ci.yaml
Depends on https://github.com/cockroachdb/homebrew-tap/pull/137
=> Add CI tests

Formula/ccloud.rb, release/ccloud-tmpl.rb, release/main.go
We have native arm binaries available for `ccloud`, so let's make them available via `brew`!
=> Add native arm binaries for ccloud

Formula/cockroach-sql.rb, Formula/cockroach.rb
Epic: None
Release justification: non-production (release infra) change.
=> release: advance to 23.1.10

.github/workflows/ci.yaml, Formula/cockroach@23.1.rb, release/cockroach-tmpl.rb
* bump version to v23.2.0
* update libgeos to 3.11.2
=> release: advance to v23.2.0

.github/workflows/ci.yaml
This PR refactors the tests workflow to use `matrix`.
=> Simplify workflow

release/cockroach-sql-tmpl.rb, release/cockroach-tmpl.rb
=> Add license files

Formula/cockroach-sql.rb, Formula/cockroach.rb
Reverts cockroachdb/homebrew-tap#226
=> Revert "release: advance to v24.2.1"

Formula/cockroach-sql.rb, Formula/cockroach.rb, Formula/cockroach@23.1.rb, Formula/cockroach@23.2.rb, Formula/cockroach@24.1.rb, release/cockroach-sql-tmpl.rb, release/cockroach-tmpl.rb
=> Install licenses depending conditionally

.github/workflows/automerge.yaml
=> automerge: pin commit for a GH Action that had its tags compromised.

.bazelversion, .github/workflows/ci.yaml, CONTRIBUTING.md, Formula/ccloud.rb, Formula/cockroach-sql.rb, Formula/cockroach.rb, Formula/cockroach@23.1.rb, Formula/cockroach@23.2.rb, Formula/cockroach@24.1.rb, Formula/cockroach@24.3.rb, Formula/cockroach@25.1.rb, WORKSPACE, release/ccloud-tmpl.rb, release/cockroach-sql-tmpl.rb, release/cockroach-tmpl.rb, release/main.go
This commit adds Linux support in addition to some minor refactoring.
Fixes: RE-885
=> Add Linux support
