- Formula/cockroach.rb
See cockroachdb/cockroach#14031 for context. Cockroach now publishes
source archives as part of the release process. These archives have
several advantages:
* Source archives are much smaller than a full Git clone of our
repository, which is advantageous for developers who want to build
from source but don't plan to hack on Cockroach.
* Homebrew strongly prefers source archives, which are easily
checksummed, to Git clones, which have mutable tags.
* The source archive is laid out to facilitate easy building from
source, which is reflected by the drastic simplification of this
Homebrew recipe.
This commit points the formula at the new source archive instead of the
Git repository and adjusts the build recipe accordingly.
> build from source archives instead of git clone

- Formula/cockroach.rb
Add a launchd configuration so that brew services can manage a single-node Cockroach cluster, if so desired.
Fixes cockroachdb/cockroach#9438.
---
This supersedes #1, which is inexplicably ignoring my force pushes. @bdarnell, I've updated the formula to serve the admin on port 26256, as discussed, and added a caveat reminding users to only use this configuration in development. The full caveats read:
```
==> Caveats
CockroachDB is a distributed database intended for multi-server deployments.
For local development only, this formula ships a launchd configuration to
start an insecure single-node cluster that stores its data under:
/usr/local/var/cockroach/
Instead of the default port of 8080, the node serves its admin UI at:
http://localhost:26256
To run CockroachDB in production, please …
```
> add launchd configuration to support brew services

- Formula/cockroach.rb
Binaries built with Xcode 8.3 immediately fail to execute with `Killed:
9`. See golang/go#19734 for details. The workaround is to pass `-ldflags
-s`; this commit accomplishes that by building with `LINKFLAGS=-s`.
Fixes #7.
> cockroach: support building with Xcode 8.3

- Formula/cockroach.rb
Reverts cockroachdb/homebrew-cockroach#9
This beta is being withdrawn because of cockroachdb/cockroach#14700 and cockroachdb/cockroach#14692
> Revert "cockroach beta-20170406"

- Formula/cockroach.rb
This changed when we rebuilt the old release as a part of reverting 0406.
Fixes #11
> Update beta 0330 sha256

- Formula/cockroach.rb
Also drop `LINKFLAGS=-s` since that's unnecessary since Go 1.8.1.
> cockroach: specify dependencies required by new build system

- Formula/cockroach.rb
The current formula chokes if jemalloc is already installed on the
system, because RocksDB is configured to prefer the jemalloc headers in
/usr/local/include.
> cockroach: backport patch to build when jemalloc is present

- Formula/cockroach.rb
We've always started CockroachDB insecurely; see #6 for a discussion of why this is reasonable. As of cockroachdb/cockroach#14703, however, we must explicitly pass --insecure; running `cockroach start` without either a cert directory or an explicit --insecure opt-in is an error.
> cockroach: pass --insecure when launching service

- Formula/cockroach.rb
This change was made in the main repo in https://github.com/cockroachdb/cockroach/commit/4d774b7.
Closes https://github.com/cockroachdb/cockroach/issues/15576.
> Remove outdated patch

- Formula/cockroach.rb
This makes `brew test` work again. Not worrying about regressions because homebrew-core automatically runs `brew test` and hopefully this merges upstream soon.
> cockroach: plumb missing --insecure flags

- README.md
The big red warning signs 🚫 led people to believe that Homebrew was no longer a
supported installation method for CockroachDB. Make the deprecation warning less
obvious to avoid confusing would-be users.
> make deprecation warning less ominous

- Formula/cockroach.rb
- README.md
Due to the move to the BSL, CockroachDB 19.2 will no longer be eligible for inclusion in `homebrew-core`. Bring this tap back up to date so we can recommend it instead.
Use our binary releases instead of building from source (a `homebrew-core` requirement) to avoid potential issues relating to `go` or other C dependency versions. 
Also add some new features: man pages and shell completion files are now installed. 
Fixes cockroachdb/cockroach#35657
> Revive our custom tap

- Formula/cockroach.rb
This field existed to ensure that this tap's version number sorted higher than homebrew-core's. Now that we're removed from homebrew-core it's no longer needed.
> Remove revision field

- Formula/cockroach.rb
The command to start a single node cluster changed at some point in the
past but was never updated here. With this change, the service will
work.
Fixes #53.
> Make the cockroach service run again.

- Formula/cockroach.rb
The sha used in this commit was generated by:
```
$  echo $VERSION
v20.2.3
$  curl https://binaries.cockroachdb.com/cockroach-${VERSION}.darwin-10.9-amd64.tgz | shasum -a 256
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 52.2M  100 52.2M    0     0  32.4M      0  0:00:01  0:00:01 --:--:-- 32.4M
5fba2230b20166eedfa566185cb55759feb05ed9d9049ad302dae03d39e671a2  -
```
> Update homebrew formula for v20.2.3

- Formula/cockroach.rb
SHA was generated by:
```bash
$  curl https://binaries.cockroachdb.com/cockroach-v20.2.4.darwin-10.9-amd64.tgz | shasum -a 256
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 53.1M  100 53.1M    0     0  27.4M      0  0:00:01  0:00:01 --:--:-- 27.3M
c03dc30d2edf134640cd161e58e36b5cafd8b53c824e71f8529e02cace006863  -
```
> Update homebrew formula for v20.2.4

- Formula/cockroach.rb
The location of the Secure a Cluster page changed. Update it to point to
the new location.
And the suggested manual command for starting cockroach needed a few
additional parameters added.
> Fix secure a cluster link and update manual command options

- Makefile
- release/cockroach-tmpl.rb
- release/main.go
Previously we had to do some manual work to update the formula -
download the file to calculate the SHA256 checksum, update various
fields to reflect the changes. This has been error prone and not
automation friendly.
This patch add a simple helper which uses a template to generate the
brew formula.
> Simplify version bump process

- Makefile
- release/main.go
* Fixed typo in make usage.
* Trim possible "v" version prefix to be more resilient.
> Fix typo, strip possible "v" version prefix

- release/cockroach-tmpl.rb
On Apple Silicon Macs homebrew packages get installed into /opt.
The default path used by cockroachdb for dynamic libraries points
to /usr/local. When starting the service via brew services the
cockroach binary can't locate the dynamic libraries unless we
add the --spatial-libs parameter to point it to the correct
library directory.
> Problem: cockroachdb can't locate libgeos.dylib when installed into /opt

- .gitignore
- BUILD.bazel
- Makefile
- WORKSPACE
- release/BUILD.bazel
- release/main.go
Previously, running the `generate` make target required Go
pre-installed. It is not the case in our Bazel CI images.
This PR adds Bazel support and builds the release version bumper binary
using Bazel before executing it. Also it explicitly passes the template
file to get rid of some compiled-in magic.
> Bazelize bump

- Formula/ccloud.rb
`ccloud` is being updated to utilize v0.2.2, which has been uploaded as a 
binary to `binaries.cockroachdb.com`. This new version update includes 
no breaking changes, and just adds telemetry that can be disabled using 
the `ccloud settings` commands.
Release note: `ccloud` is updated to `v0.2.2` to include optional telemetry.
> ccloud: update ccloud to v0.2.2

- Formula/ccloud.rb
This PR updates the 2.2 patch silently due to a non 
breaking change of a telemetry event, specifically 
adding an `Initiated` event type for when certain 
multi step commands are run.
> ccloud: update ccloud sha for silent version upgrade

- Formula/ccloud.rb
ccloud is being updated to v0.2.4, the new binary is uploaded to binaries.cockroachdb.com. This new version update includes no breaking changes. The new version adds a new shorter hostnames in the connection URLs of the serverless clusters
Release note: ccloud is updated to v0.2.4 to allow shorter hostnames for serverless connection strings.
> ccloud: update ccloud to v0.2.4

- Formula/ccloud.rb
This update just includes some updated error telemetry.
> ccloud: bump ccloud to 0.2.5

- Formula/ccloud.rb
This update includes the changes needed for Cloud Cluster SSO and allows users to run `ccloud auth login` remotely.
> ccloud: bump ccloud to 0.3.6

- Formula/ccloud.rb
The updated version allows cluster SSO for serverless clusters and lets ccloud auth work with Safari without downloading a file.
> ccloud: bump ccloud to 0.3.7

- Formula/cockroach.rb
- release/cockroach-tmpl.rb
Fixing this warning message:
```
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the cockroachdb/tap tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
/usr/local/Homebrew/Library/Taps/cockroachdb/homebrew-tap/Formula/cockroach.rb:62
```
> Use service instead of deprecated plist_options

- .github/workflows/ci.yaml
- Formula/cockroach@22.2.rb
- README.md
- release/main.go
This allows homebrew to install older cockroach versions using the same brew syntax.
I didn't do the earlier versions as they have no ARM versions, and would require a large template change.
Refs #42
> add @22.2 build

- Aliases/cockroach@23.1
This currently aliases to cockroach using a symlink.
This is how it's done in the homebrew repo.
> add alias for cockroach v23.1

- Makefile
Now that we can use the same template to generate `cockroach.rb` and `cockroach@22.2.rb`, we should also update the helper Makefile to use the same template for them.
> build: fix template usage in Makefile

- Formula/cockroach-sql.rb
- Formula/cockroach.rb
- Formula/cockroach@22.2.rb
This includes both v23.1.6 + v22.2.12
> release: advance CRDB version to v23.1.6 + v22.2.12

- Formula/cockroach-sql.rb
- Formula/cockroach.rb
> release: released CockroachDB version 23.1.9. Next version: 23.1.10

- .github/workflows/automerge.yaml
This change marks PRs created by `cockroach-teamcity` ready to be merged after all checks are passed.
> Automerge version bumps

- release/cockroach-sql-tmpl.rb
- release/cockroach-tmpl.rb
This pr removes the version constraint to install the license files. It will not affect the current versions, only the formulas that will be regenerated as a part of the next releases.
> Remove license version constraints

- .github/workflows/ci.yaml
- Formula/cockroach@23.2.rb
This PR removes support for 22.2 and adds support for 23.2.
https://cockroachlabs.atlassian.net/browse/REL-930
> Add 23,2, drop 22.2

- .github/workflows/automerge.yaml
The existing action spews some deprecation warnings, better to switch to something well maintained.
> automerge: use changed-files action

- .github/workflows/ci.yaml
- Formula/cockroach@24.1.rb
This PR adds support for 24.1:
Now that we've published a 24.2 binary for download (v24.2.0), we need to create a separate homebrew formula for 24.1: `Formula/cockroach@24.1.rb`.
* (For reference/comparison, refer to [/Formula/cockroach@23.2.rb](https://github.com/cockroachdb/homebrew-tap/blob/master/Formula/cockroach%4023.2.rb)
> Add support for 24.1.
